languageCode = "ja"
title = "渡辺 早稀 | Saki Watanabe"

contentdir = "content"
publishdir = "public"
builddrafts = true
baseUrl = ""
canonifyurls = true
author = "Saki Watanabe"
theme = "pixyll"
disqusShortname = "sitename"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  google_analytics_id = "XX-XXXXXXXX-X"
  twitter_username = "younippon"
  paginate = true
